# Generated by Django 4.0.2 on 2022-02-11 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consume',
            options={'verbose_name': 'consume'},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'food', 'verbose_name_plural': 'foods'},
        ),
    ]
